bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),


]

blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='post'),
    # path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('<slug:slug>/', views.post_detail, name='post_detail')
]

computer_pc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
STATUS = ((0, "Draft"), (1, "Publish"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_post')
    updated_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']       
 
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
        )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Post
from .forms import CommentForm

# Create your views here.


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/post.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


def post_detail(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

blog/templates/blog/post.html
{% extends "base.html" %} 


{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{%endblock%}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block page_header %}
    <div class="container header-container d-flex justify-content-center">         
        <div class="row">
          <div class="col-12 col-md-10 card mt-3 " style="min-width: 100%;">
            <div class="card-body mb-4" >
              <h1 class="card-title">{% block title %} {{ post.title }} {% endblock title %}</h1>
              <p class="card-text text-muted">{{ post.author }} | {{ post.created_on }}</p>
              <p class="card-text ">{{ post.content | safe }}</p>
            </div>
          </div>    
        </div>
    </div>

      
  
{% endblock %}
{% block content %}
<!-- comments -->
<div class="container d-flex justify-content-center">
      <div class="row ">
        <div class="col-12 col-md-10 card mb-4 mt-3 "style="min-width: 100%;">
            <div class="card-body" >
              
              <h2>{{ comments.count }} comments</h2>

              {% for comment in comments %}
                <div>
                  <p class="font-weight-bold">
                    {{ comment.name }}
                    <span class=" text-muted font-weight-normal">
                      {{ comment.created_on }}
                    </span>
                  </p>
                  {{ comment.body | linebreaks }}
                </div>
              {% endfor %}
            </div>
        </div>
      
      
        <div class="col-12 col-md-10 card mb-4  mt-3 " style="min-width: 100%;">
          <div class="card-body">
            {% if new_comment %}
            <div class="alert alert-success" role="alert">
              Your comment is awaiting moderation
            </div>
            {% else %}
            <h3>Leave a comment</h3>
            <form method="post" style="margin-top: 1.3em;">
              {{ comment_form.as_p }}
              {% csrf_token %}
              <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
            </form>
            {% endif %}
          </div>
        </div>
      </div> 
    </div>  

{% endblock %}